error form processintwernal
FATAL: System.NullReferenceException: Object reference not set to an instance of an object.
   at AzureValidator.<ProcessInternal>d__3.MoveNext() in AzureValidator.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewPlugin.<Process>d__11.MoveNext() in NewPlugin.cs:line 67
Error: Plugin azure-validator failed.
    at ...
    at ...
    at ...
    at ...
